# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PassworkCli < Formula
  desc "Command Line Interface tool for https://passwork.me/"
  homepage "https://github.com/Sebor/passwork-cli"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sebor/passwork-cli/releases/download/v1.0.4/passwork-cli_1.0.4_darwin_amd64.tar.gz"
      sha256 "4a792df56bfdc55d9f71611eb4244b229a24d6919060936bacf61dac4c7540df"

      def install
        bin.install "passwork"
        prefix.install "README.md"
        bash_completion.install "autocomplete/bash_autocomplete" => "passwork"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sebor/passwork-cli/releases/download/v1.0.4/passwork-cli_1.0.4_darwin_arm64.tar.gz"
      sha256 "a554fecb8a95f4b41e795cb73f67572772315099320411d72826c0b8d135d962"

      def install
        bin.install "passwork"
        prefix.install "README.md"
        bash_completion.install "autocomplete/bash_autocomplete" => "passwork"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sebor/passwork-cli/releases/download/v1.0.4/passwork-cli_1.0.4_linux_arm64.tar.gz"
      sha256 "4ee2462b8e79a1029cb007d3a6b084195640d980d71c51352e8620db5bb0a475"

      def install
        bin.install "passwork"
        prefix.install "README.md"
        bash_completion.install "autocomplete/bash_autocomplete" => "passwork"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Sebor/passwork-cli/releases/download/v1.0.4/passwork-cli_1.0.4_linux_amd64.tar.gz"
      sha256 "52f55f18215e9aece33d1a9c582e008733bbc152c5edddcfb2a44d094ccc0a9f"

      def install
        bin.install "passwork"
        prefix.install "README.md"
        bash_completion.install "autocomplete/bash_autocomplete" => "passwork"
      end
    end
  end
end
