# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PassworkCli < Formula
  desc "Command Line Interface tool for https://passwork.me/"
  homepage "https://github.com/Sebor/passwork-cli"
  version "1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Sebor/passwork-cli/releases/download/v1.1.2/passwork-cli_1.1.2_darwin_arm64.tar.gz"
      sha256 "0940621a09d13363c44b963714f6ff1407ebad2f200caf7424f52893fcb19b08"

      def install
        bin.install "passwork"
        bash_completion.install "autocomplete/bash_autocomplete" => "passwork"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Sebor/passwork-cli/releases/download/v1.1.2/passwork-cli_1.1.2_darwin_amd64.tar.gz"
      sha256 "a553f38ba7a62cfd67485b0565adda08dedc63966ba48f10635a56f41d33ce5c"

      def install
        bin.install "passwork"
        bash_completion.install "autocomplete/bash_autocomplete" => "passwork"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sebor/passwork-cli/releases/download/v1.1.2/passwork-cli_1.1.2_linux_arm64.tar.gz"
      sha256 "76bec97b2a428903df799fbb7cc6807756decc970dc7c745d032debe55a68bb7"

      def install
        bin.install "passwork"
        bash_completion.install "autocomplete/bash_autocomplete" => "passwork"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Sebor/passwork-cli/releases/download/v1.1.2/passwork-cli_1.1.2_linux_amd64.tar.gz"
      sha256 "89d5587abfa1baabef08cf1d5031affe9fd097c8a8bade7d39272e9745807b56"

      def install
        bin.install "passwork"
        bash_completion.install "autocomplete/bash_autocomplete" => "passwork"
      end
    end
  end
end
